max_workers: ${CONCURRENCY:100}

DB_POOL_SIZE: ${DB_POOL_SIZE:20}
DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW:50}
DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT:120}

DB_URIS:
  "monitoring:Base": ${DB_URI:postgresql://${DB_USER:postgres}:${DB_PASSWORD:password}@${DB_SERVER:localhost}/${DB_NAME:monitoring}}

WEB_SERVER_ADDRESS: ${SERVER_ADDRESS:0.0.0.0}:${SERVER_PORT:8003}

REDIS_URL: redis://${REDIS_SERVER:127.0.0.1}:${REDIS_PORT:6379}/${REDIS_DB:0}
