"""added redis message id to mixins

Revision ID: c9b905569623
Revises: fa9201a8d71b
Create Date: 2020-01-02 17:04:07.947206

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c9b905569623"
down_revision = "fa9201a8d71b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_requests", sa.Column("redis_message_id", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_requests", "redis_message_id")
    # ### end Alembic commands ###
